### ISSUE TITLE
Java Runtime  old version 

### ISSUE THREAD

**Issue by VuDn5** [jacamars/Newbidder#21]
Good day all. 
I build  Bidder with a docker-compose , but i have error:
`
wait-for-it.sh: minio:9000 is available after 0 seconds
Error: LinkageError occurred while loading main class com.jacamars.dsp.rtb.bidder.RTBServer
        java.lang.UnsupportedClassVersionError: com/jacamars/dsp/rtb/bidder/RTBServer has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

`
.
it's have too many time when convert JDK from 11 to version 17 Java,
Please fixed,

I thank you for amazing project. ^-^

**Comment by levynir** [comment]
I am getting the same error running the docker-compose images

**Comment by VuDn5** [comment]
> I am getting the same error running the docker-compose images

Sorry, i can't help you.  
i'm quit project and choose another repo.
